import { Inter } from 'next/font/google';
import './globals.css';
import Link from 'next/link';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  const links = ['home', 'drinks'];
  return (
    <html lang="en">
      <body className={inter.className}>
        <nav>
          <ul className="flex gap-8 justify-center py-4 mb-0 bg-gray-300">
            {links.map((link) => {
              return (
                <Link
                  key={link}
                  className="btn bg-teal-400 p-2 rounded-md uppercase"
                  href={`/${link === 'home' ? '' : link}`}
                >
                  <li>{link}</li>
                </Link>
              );
            })}
          </ul>
        </nav>
        <main className="w-11/12 mx-auto flex justify-center mt-20 ">
          {children}
        </main>
      </body>
    </html>
  );
}
